### ISSUE TITLE
Reboot index

### ISSUE THREAD

**Issue by manyinsects** [rustbridge/reboot#1]
## What is this?

As you might have noticed, RustBridge has had next to no activity over the last 3-4 years. There's a bunch of reasons for this that I'm not going to get into, but it would be nice to bring some momentum into the project once more.

This issue is meant to keep track of work needed for a "reboot" of RustBridge. What I would consider the "finished state" of this, I'll outline in the next section, and some of the points listed are more nice-to-have, but the idea is that if everything comes together, it'll be not only possible, but also pretty straightforward for people to host their own RustBridge events.

## The goal

There's no explicitly finished state that I can define at this point in time (when authoring this issue), but some things that I believe would constitute a successful reboot of RustBridge are:

- __Bring everything up to speed__. The website, and a bunch of the materials are stuck in pre-2019 land, it would be good to move to a newer, Rust-based static site generator, for example. The curriculum materials also need a pass on current Rust practices.
- __Overhaul docs__. While docs exist in the current state, we might need waaaaay more of them to help people plan their own events. Specific things it'd be a good to get:
  - Lesson plans (or "curriculums"), I think the only one linked on the website is lost?
  - Specific information for organizing, we can take information from other, similar initiatives (other *bridges, for example)
  - more?
- __Figure out our place in the project__. This is mostly a me-issue, but since the Community Team doesn't formally exist anymore, but we want to keep RustBridge as an official Rust Project thing, I have to figure out what to do with the new governance structure.
- __Provide help for people who organize an event__. Organizing an event is stressful and a lot of work, but we've done it a bunch of times, so we should be able to do something to help prospective organizers out, whether that's human-to-human assistance or some form of tools.
- __Prevent stagnation__. This is probably the hardest part to figure out? We don't want this to happen again, so we might want to enact some measures against it (disclaimes: I have _no_ idea what this could look like at the moment)

I think with all that set, we should be on a pretty good path. Obviously, it's a lot of work, so I think setting a time frame is useless, especially since everyone involved is doing this in their free time.

## To do

Here's the massive task list where we can distribute work. More tasks may get added as time goes on! Feel free to create separate issues for each task you want to talk about further, just make sure to link them back here.

- __Website__
  - [ ] Transition to a new SSG (static site generator) -> #2 
    - [ ] Figure out which one (probably one of the Rust-based ones?) -> #2
    - [ ] Take stock of existing material and formulate a migration plan -> #2
    - [ ] Do the migration
    - [ ] Write up maintenance docs (I guess...?)
  - [ ] Do we want to use a separate docs generator? Something like Docusaurus, since we'll likely mostly have docs
  - [ ] Remove the whole chapter part, that was an experiment that didn't really work out
  - [ ] Add a page listing all RustBridge events that we can think of
- __Organizational stuff__
  - [x] Take stock of the "team", create a `legacy` GitHub team, with the option for legacy team members to become active (@shadows-withal)
  - [ ] Probably write up some sort of document detailing what the "team" even is, and the procedures surrounding it
  - [ ] Clean up the "team" in the `rust-lang/team` repository (@shadows-withal)
  - [ ] Figure out whether we want to charter as anything (team? wg? idk what else there is) under the new governance structure
  - [ ] Move active people into a new "team" team (confusing, I know)
  - [ ] Clean up the GitHub a little bit, archive old repositories that serve no more use
- __Materials__
  - [x] Intro to Rust:
    - [x] Merge with the "new old" version that @ashleygwilliams made for the EuroRust 2023 RustBridge
    - [x] Move to a new SSG, ideally the same one that the website ends up using
  - [ ] Snake game project:
    - [ ] Modernize? Move to unified "docs" infrastructure maybe? Need to look at this more closely
  - [ ] CLI project:
    - [ ] Move out of `eurorust` repo into its own thing
    - [ ] Condense a bit
  - [ ] All "curriculum pieces" should have a minimum time investment and a maximum time investment (so that we can say "this will take min. X hours, max. Y hours)
  - [x] See if we can't unify the presentational tool for the slides for each material

## Helping out

Did anything here catch your fancy? Fantastic! We'd love to have you help out, it's a lot of work, and the more people work on it, the sooner we'll have a great experience for organizers and learners. A good first step is to create a new issue for the thing you'd like to work on, or if an issue already exists, to raise your hand in there. As time goes on, we may also have some sort of chat platform that you can reach out to people on

**Comment by ultrasaurus** [comment]
@shadows-withal 👋 hello from @bridgefoundry nee @railsbridge -- can help with....
- [ ] post on social media about this issue?  (we did most early organizing on Twitter, which was very effective for finding volunteers for stuff like this). I've personally moved entirely to Mastodon, but can post on all the things
- [ ] *Provide help for people who organize an event* <-- we were *just* talking about this today.  One idea is to get people who organized events in other regions and/or for other *Bridges to mentor new organizers.  Would that be of interest?
- [ ] *Prevent stagnation.*  lots of ideas on this, nothing magical yet some experience with what has worked and not worked for in the past -- and lots of the *Bridges are facing how to revive since there was an understandable gap in most activities during the height of the pandemic
- [X] also personally, I've been learning Rust on-and-off for a while, so I'll create an issue to work on some curriculum: https://github.com/rustbridge/reboot/issues/3 <-- comment on here (or suggest alternate tracking if that wasn't the right thing to do!)

**Comment by ultrasaurus** [comment]
also just saw this Lightning talk [How to run a RustBridge event](https://www.youtube.com/watch?v=piaXhwGH-Gw) by @jonknapp -- three years old, yet still relevant!    I think it would be inspiring to new organizers if y'all want to link to it.

**Comment by manyinsects** [comment]
heya @ultrasaurus! admittedly, progress on this has been slower than I intended - lots of stuff to do at work, but basically all of your suggestions sound good. i think maybe a good time to drum up some support is over the holidays/between the years? i know i can dedicate some more time there. i do also like the idea of more experienced organizers acting as a sort of contact to provide support to new organizers - happy to hear more about how that works in other *bridges

**Comment by palutz** [comment]
Hi,
I helped to run another bridge years ago (Scala Bridge) and loved the idea. I was thinking about to do a Rust Bridge based on that, and very happy someone already had the same idea and sort it out a lot of things. 
Anyhow, I'm Stefano, based in the UK, near-ish London. I'm happy to help and see if we can create a London chapter

**Comment by palutz** [comment]
Hi @shadows-withal 
I saw your answer in the other issue. Any update also on this one?

**Comment by manyinsects** [comment]
hey @palutz, sorry, been pretty bad at looking at my notifications the last weeks :) as it stands, the "chapter" system is pretty much nonfunctional, and the whole project is sort of dormant, so i'm a bit hestitant to say "go for it" (if you want to though, then don't let me stop you -- i'm just worried that we don't have enough resources/help to support you at the moment)

**Comment by palutz** [comment]
@shadows-withal don't worry, I understand and happy to see you were able to come back to me.
About resources: I think you have a lot of resources, and it is just a matter of planning.
My experience (with another Bridge, ScalaBridge) is to try running multiple events at the evening for a couple of hours (up to 3 hours) and create a group of "students". It is NOT easy, but if you are open I would like to try and share then experience and materials (and ask for help/feedback/comments/...)

**Comment by manyinsects** [comment]
Took a stab at modernizing the intro today, culminating in this: https://github.com/rustbridge/a-very-brief-intro-to-rust/pull/23
