### ISSUE TITLE
Moving to a new SSG Tracking Issue

### ISSUE THREAD

**Issue by jdonszelmann** [rustbridge/reboot#2]
The [Rustbridge website](https://rustbridge.com/) is currently using Jekyll, a ruby based static site generator. We would like to move away from this (see #1) in favour of some Rust based SSG. As far as I can see, there are sort of three options, though please correct me if I'm wrong. All of these are markdown based, which is nice.

* [cobalt.rs](https://github.com/cobalt-org/cobalt.rs) I hadn't heard of this one before. It seems neat, and can do a lot of what Zola can do as well, but it also seems (at first glance, I hope I'm not misrepresenting anyone) a bit less mature. For Zola I can see various cool themes available, and not so quickly for cobalt. 
* [mdbook](https://github.com/rust-lang/mdBook) Although great for *books*, I don't think this is entirely the kind of site we are going for.
* [zola](https://github.com/getzola/zola) To me this looks like the option I feel most comfortable with. It's both easy to get nice themes as well as customise it yourself. I've heard many good stories about the project.

I propose we try and migrate the old website to Zola first, I think it's not too hard a process to just plug all the markdown files from the old site into a new repo, which we could just host on GitHub pages for a little bit until we're happy enough with it to put it under <https://rustbridge.com/> However, because the old website was also already hosted under GitHub pages, that's not so easy in the old repo. We can do two things: move to another repo for testing temporarily, or just not deploy on pages for now and just run it locally. If anyone has a strong preference, let me know :)

Once we're happy with that, we can actually start making changes to the website. Which changes, we probably need to discuss more in-depth later, though some have been mentioned in #1 already.

If that all sounds reasonable to you too @shadows-withal, I wouldn't mind taking some of these steps. Below, I put some progress checkmarks, according to this plan, but more sub-points can be added when we discover them.

 * [x] Agree to this (for now pretty bare-bones) migration plan
 * [ ] Switch the old content to Zola
 * [ ] Set up GitHub actions to deploy to a temporary GitHub pages (if all agree)
 * [ ] Sub-list: what immediate tasks we have before we want to release the on <https://rustbridge.com/>
     * [ ] Remove "Chapters"
     * [ ] Remove some broken links like the one to rustfest berlin
     * [ ] Implement checks for that (I know there is one for mdbook that checks all links whether they're broken)
     * [ ] Possibly implement some less trivial changes before we release to <https://rustbridge.com/> like fixing some tasks under >materials in #1 
 * [ ] Release on <https://rustbridge.com/>

**Comment by manyinsects** [comment]
I would agree with using Zola! I think it can get us most of the way there, maybe modulo the docs if we decide to factor them out into some sort of docs-specific SSG.

**Comment by vasfvitor** [comment]
hi, how is it the migration going? This weekend, as an experiment, I made a quick attempt at migrating (as first timer both in Zola/Tera and Jekyll/Liquid) but it's nowhere near finished, well, the index page with the footer (and links) is almost 1:1, but not ready because of some issues with markdown
